### ISSUE TITLE
CRITICAL: codecov does somehow not check all tests in the test suite right now.

### ISSUE THREAD

**Issue by Gewerd-Strauss** [Claudius-Appel/duflor#28]
WHY?

**Comment by Gewerd-Strauss** [comment]
consider struct under https://github.com/wlandau/instantiate/blob/main/.github/workflows/cover.yaml

**Comment by Claudius-Appel** [comment]
closed in 7b9f74baaef77cbd6bcb736f002a0389661ffa72
